leachim6/hello-world

- j/json.json
Because markup languages count too!
> Add json.json

- w/wren.wren
Hi,
I'm adding yet another "hello world" program, but this time in wren language.
You can read more about it at: http://munificent.github.io/wren/
Regards,
Piotr
> adding hello world in wren language

- g/googleappscript.gs
Hello World in Google Apps Script.
Test at [http://www.google.com/script/start/](http://www.google.com/script/start/)
> Added GoogleAppScript.gs

- f/fog.fog.md
Printing in fog is done by <ins>underlining text</ins>.
> added fog lang

- c/c.c
not need to put "void" to function properly
> excluded "void" in function "main"

- f/fjoelnir.fjo
Icelandic programming language from the 80s
more about it here: http://en.wikipedia.org/wiki/Fj%C3%B6lnir_(programming_language)
> Added Fjölnir/Fjoelnir (.fjo)

- i/idris.idr
> Added idris example

- a/agda.agda
[Agda][wiki] is a dependently typed programming language. 
[wiki]: http://wiki.portal.chalmers.se/agda/
> Added Agda

- o/Orc.orc
- y/yolang.yo
> Adds a couple programming languages

- j/Java.java
Renamed java to Java based on the Java language convention: Classes are uppercase.
> Update and rename java.java to Java.java

- z/zepto.zp
Added hello world in the Scheme derivative [zepto](http://zepto.veitheller.de/).
> added zepto

- u/Ubercode.cls
Hello world program in Ubercode high level programming language designed by Ubercode Software added.
Reference:
[Ubercode Wikipedia](https://en.wikipedia.org/wiki/Ubercode)
[Ubercode Official Website - (Source code)](http://www.ubercode.com/hello-world-program.html)
> Hello world in Ubercode added

- a/assembler_m68000_amigaos.asm
An example in M68000 machine language, for AmigaOS
> M68000 AmigaOS

- d/Dyvil.dyvil
Added the HelloWorld class written in the [*Dyvil*](https://github.com/Clashsoft/Dyvil) programming language.
> HelloWorld in Dyvil

- c/css.css
> [css.css] Add tab

- e/emoticon.emoticon
- q/qwerty.qwerty
Golfed emoticon.emoticon down a bit more.
Update qwerty.qwerty to showcase the upcoming language more.
> Couple of changes

- p/perl6.p6
Another attempt to add Perl 6.
Used *.p6 extension and `use v6` to differentiate from other Perl file
> Add Perl 6 Hello World

- c/cypherNeo4j.cypher
Cypher is Neo4J query language.  Here I'm creating two Nodes (Hello and World, both of type Words) and linking them with relationship "space", as it looks nice on a graph.
More:
1. http://neo4j.com/developer/cypher-query-language/
2. https://en.wikipedia.org/wiki/Cypher_Query_Language/
> Cypher, Neo4j, creates a Hello-:space->World! graph

- m/mongo.shell
MongoDB can be interacted with in a number of ways. Most common for prototyping is MongoDB shell, which has number of built-in functions, among them print.
> Printing Hello World! in MongoDB shell

- e/~English.ext
- g/glass.glass
- s/slashes.slashes
Added ~English, Glass, and /// (`slashes`).
> Add some esoteric programming languages

- a/assembler_nasm_linux64.asm
It's based on the i386 version, just ported to x86-64 with a bit of microoptimizations for size.
> Add nasm x86-64 linux version

- p/php.php
`echo` is a lot more used than `print`.
Also, in a PHP-only file, no `?>` is required.
Simple is better, IMHO.
> Simplify php.php

- a/assembler_mips.asm
created MIPS assembly hello world program.
> add mips assembly

- i/ink.ink
hello world program added in ink scripting language. 
Reference: https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#the-simplest-ink-script
> ink.ink file added

- t/plain-text.txt
How could you forget about the all know, default... PLAIN TEXT!
> Created plain text!

- x/lolcode.lol
LOLCODE can be found [here](http://lolcode.org/).
> Add LOLCODE language example

- a/alda.alda
A music programming language for musicians.
https://github.com/alda-lang/alda/blob/master/examples/hello_world.alda
> alda.alda added

- a/acs.acs
(Uses ZDoom header, but should work in Hexen too)
> Add "Hello, World!" in Action Code Script

- t/TTCN3.ttcn
Hi,
One more: Testing and Test Control Notation 3
http://www.ttcn-3.org/
https://en.wikipedia.org/wiki/TTCN-3
BR/ Maciej
> Added TTCN3

- h/hodor.hd
A snippet of 'Hello, World!' in [Hodor](http://www.hodor-lang.org/).
> Add 'Hello, World!' in Hodor.

- c/ceylon.ceylon
Hello World in Ceylon programming language. The code from [Ceylon Documentation](http://ceylon-lang.org/documentation/1.2/tour/basics/).
> ceylon.ceylon

- r/reason.re
https://github.com/facebook/reason
> Add reason

- s/stanza.stanza
New language for UC Berkeley: http://www.lbstanza.org
> Add Stanza.

- m/mathematica-online.nb
Perhaps mathematica.nb would be a better name since it's runnable on local copies of Mathematica as well.
> Added Mathematica notebook made on Mathematica Online.

- b/batsh.batsh
Batsh is a language that compiles to bash scripts or Windows batch files (.bat).
This allows to run the resulting script without any dependencies on target
platform.
More info about batsh:
http://batsh.org/
https://github.com/BYVoid/Batsh
> Added `batsh.batsh` file in Batsh language.

- c/crystal.cr
> Add Crystal

- f/forth.fth
The previous example didn't actually print anything, it just defined a "word" (function) called `HELLO` and never called it. You could either call the function (just add `HELLO` on a new line), but more simply and idiomatically for just printing something you can use `.( string)` which I've done here.
You can try this in an online Forth REPL at https://repl.it/languages/forth
> Make Forth example actually *print* the string

- v/visualfoxpro.prg
Multiple Visual FoxPro samples, taken from https://en.wikipedia.org/wiki/Visual_FoxPro
> Visual FoxPro

- s/S-algol
https://en.wikipedia.org/wiki/S-algol
> St andrews algol

- s/self.self
Thanks for doing this @leachim6 !
> adds Self to the examples

- j/jsx.js
The use of pure functions for rendering stateless components is [highly encouraged](https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d) as well as it makes for an easier and more concise example.
This also makes it "real" JSX as it decouples the component itself from React, that is only responsible for rendering now.
> use pure function instead of creating class

- s/sparql.sparql
> Create Hello World in SPARQL query language

- b/battlestar.bts
Added Battlestar.
More Hello World snippets here: http://rosettacode.org/wiki/Hello_world/Text
> Add Battlestar

- x/lolcode.lol
It is already present, correctly, in folder 'l'
> Remove lolcode.lol from folder 'x'

- e/hello-html.elm
- add a hello world example for Elm ( from from http://elm-lang.org/examples/hello-html )
> Add "hello world" example for Elm

- p/php.php
Change double quotes to single quotes due  to no necessity of doing interpolation here. Basic example should just show basic display of hello world, without additional feature. it also has some performance difference
> Removed unnecessary interpolation

- s/streem.strm
https://github.com/matz/streem
> add streem

- a/aiml.aiml
Create 'Hello BOT' in AIML Bot Lang
> Create AIML Bot Lang

- n/nit.nit
Add the Nit programming language, as seen here: https://nitlanguage.org/
> Add Nit language.

- a/assembler_vax_ultrix.asm
Yet another assembler, looks like quite a nice one, except, that's some weird calling convention.
> Added VAX assembler for Ultrix

- a/arduino.ino
Removed redundant `void loop() {}`
> Simplified arduino.ino

- g/Green-Marl.gm
Green-Marl is a domain specific language for graph analysis algorithms.
http://www.cl.cam.ac.uk/~ey204/teaching/ACS/R202_2012_2013/papers/S7_Network_Structure/papers/hong_asplos_2012.pdf
> add Green-Marl "Hello World" procedure

- c/coconut.coc
The Coconut language is an extension to Python; however it's a language in itself.
> Coconut language

- c/cobol.cbl
- Start statements after seven columns.
- Use lowercase, as it is less hideous.
- Terminate `display` properly with `end-display`.
- Make the `program-id` field match the file name.
> Make cobol.cbl a well-formed COBOL program.

- m/maxscript.ms
Heh, finally, a language that's not been added yet. :)
MAXScript is the built-in language of [3D Studio Max](https://en.wikipedia.org/wiki/Autodesk_3ds_Max), a 3D graphics suite and a heavyweight in the architectural/visualisation industry. More about it [here](http://help.autodesk.com/view/3DSMAX/2016/ENU/?guid=__files_GUID_46ECBAD7_35E9_43BD_8A8C_849772924805_htm), and there's an Atom language package for it [here](https://github.com/Alhadis/language-maxscript). =)
> Add an example for MAXScript

- c/hello-world.curry
Curry  is an experimental functional logic programming language , based on the Haskell language. It merges elements of functional and logic programming, including constraint programming integration.
https://en.wikipedia.org/wiki/Curry_(programming_language)
> hello world in curry language

- CONTRIBUTING.md
- README.md
- README_nolist.md
- list_langs.rb
I didn't list the languages yet (i.e. didn't run the script) because certain files (i'm looking at you, brainf*ck) cause markdown problems or don't format correctly (for example "brainf-ck" get formatted to "Brainf Ck" -_-). Someone (probably me) needs to go through and fix the rogue filenames, but until then let's just wait for the author to merge this request :)
> Automatic language listing & CONTRIBUTING.md

- a/assembler_tasm_dos.asm
Tested with Turbo Assembler in DosBox (default settings).
> Created assembler_tasm_dos.asm

- c/c.c
To the author: Sorry for spamming you with pull requests, but look on the bright side: I find all the problems for you, and you can accept them with just a few clicks ;)
> Added missing whitespace

- p/pharo.st
For Pharo programming language: http://pharo.org/
> Add Pharo's hello world

- c/cheddar.cheddar
Added "Hello World" in cheddar programming language: http://cheddar.vihan.org
> Added Cheddar

- CONTRIBUTING.md
- README.md
- list_langs.py
Added a warning to `CONTRIBUTING.md` that all changes to the readme should be done in `README_nolist.md`, not `README.md`.
> list_langs.py now makes the languages in the listing links to the actual files, and added some info to CONTRIBUTING.md

- list_langs.py
> Update list_langs.py to exec via python3 from env

- k/kitten.ktn
> Kittenlang

- list_langs.py
#399 was overwritten by #401 :(
> Re-submit #399

- d/Dyvil.dyv
- d/Dyvil.dyvil
Updated the Dyvil Hello World program to the latest language version (v0.31.0).
> Update the Dyvil Program

- README.md
- README_nolist.md
- list_langs.py
Removed unnecessary comment here, added some punctuation there. README.md is beautiful now.
> Prettify readme & some maintenance

- README.md
- k/kotlin
Removed duplicate Kotlin file.
The removed duplicate file also didn't specified the file extension.
> Remove duplicate Kotlin file

- README.md
- a/assembler_hla.hla
Hello Word using the [HLA](https://en.wikipedia.org/wiki/High_Level_Assembly) assembly language.
> Added High Level Assembly implementation

- g/gravity.gravity
Gravity language: https://marcobambini.github.io/gravity/
> Added Gravity

- c/cson.cson
Added a hello world for the language cson.
> added cson

- n/mathematica.nb
> hello world in Wolfram_Language of mathematica

- a/awful.yuk
This changeset adds an implementation in _awful_, which is a horrible-looking scripting language I made a few years ago due to extreme boredom.
> Add an implementation in awful

- README.md
- q/qsharp/Driver.cs
- q/qsharp/qsharp.qs
I'm not sure the best way to add this, or even if it should be added. In qsharp, you don't print anything using qsharp, you'd print in the csharp driver. Let me know what you guys think.
> added qsharp

- a/assembler_bootsect.asm
I created new file called `assembler_bootsect.asm`. A little Operating System that prints **Hello world!** on the screen. You can assemble using nasm and boot it using qemu
> Support for new Operating System

- b/bolgefuck.bf
Add 'hello world' in bolgefuck (https://github.com/1f604/bolgefuck)
> Add 'hello world' in bolgefuck (https://github.com/1f604/bolgefuck)

- p/parser.p
[Parser](https://en.wikipedia.org/wiki/Parser_(CGI_language)) is a free server-side language language developed by Art. Lebedev Studio.
> "Hello, World!" in Parser

- README.md
- p/pure_data.pd
> Add Pure Data (see https://puredata.info)

- f/fstar.fst
Please welcome [F*](https://www.fstar-lang.org/).
> Add FStar example.

- a/arc.arc
Added Hello World in Arc, a terse dialect of Lisp created mainly for the Hacker News website.
> Add Hello World in Arc

- m/mips.s
> Added MIPS

- t/raffalang.bro
> RaffaLang - Language

- l/lcoffee.lcoff
github.com/paulohenriquesn/lcoffee
> LCOFFEE - Language

- README.md
- v/velato.ly
Velato is an esoteric programming language by User:Rottytooth,
> Velato programming language

- README.md
- r/rockstar.rock
Check https://github.com/dylanbeattie/rockstar
> Add rockstar

- README.md
- a/Apex.cls
Hello World from Apex (Salesforce)
> Hello World from Apex (Salesforce)

- a/arduino.ino
Arduino15/packages/arduino/hardware/avr/1.6.21/cores/arduino/main.cpp:46: undefined reference to `loop'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Uno.
> FIX loop function

- p/python3.py
update python3.py shebang line
> update python3.py shebang line

- m/modiscript.chai
Modi script is a scripting language made to mock the indian prime minister
https://github.com/VPanjeta/ModiScript
> modiscript.chai added

- README.md
- v/VBA.vba
List of changes:
* Created an interactive link to CONTRIBUTING.md in README.md
* Replaced the broken link in the description of this repo to the wiki with a link to CONTRIBUTING.md
> Documentation fixes

- h/html.html
Made it go through the W3C validator. 
Optimized and ready for people using screen-readers.
> Make more Htmly

- m/malbolge.mbg
https://en.wikipedia.org/wiki/Malbolge
> Changed Hello World according to Wikipedia

- README.md
- s/starlark.star
[Starlark](https://github.com/google/starlark-go) -- new language from Google. It's lightweight Python with parallelism for dynamic configuration files.
[There is full specification](https://github.com/google/starlark-go/blob/master/doc/spec.md)
> Added starlark

- README.md
- a/avisynth.avs
Avisynth script is a scripting language for frameserving.
This script doesn't technically "print" "Hello World" but return a still video clip with a message read "Hello World".
> Added AviSynth

- README.md
- inkling.ink
adds hello world in [inkling](https://github.com/mpeglerg/Inkling)
> Add Inkling

- c/c++.cpp
Drop endl which is not newline and the return 0 that is implicit.
> More idiomatic C++

- c/c++.cpp
> Use namespace

- README.md
- d/deno.ts
A secure JavaScript and TypeScript runtime https://deno.land/
> Added Deno

- README.md
- d/东北.dongbei
- s/上海话.shanghai
Added Dongbei and Shanghai
Dongbei: https://github.com/zhanyong-wan/dongbei
Shanghai: https://github.com/cabuliwallah/shanghai-from-dongbei
Fix for #733 .
> Added Shanghai

- README.md
- p/providex.vim
`ProvideX is a computer language and development environment derived from Business Basic (a business oriented derivative of BASIC) in the mid-1980s.` according to [wikipedia](https://en.wikipedia.org/wiki/ProvideX).
I used materials explained syntax of this language from [Site](https://codelani.com/languages/providex.html)
> Added ProvideX

- m/minecraft
Changed @p to @a and removed the command slash (bad practice)
> Fix Minecraft

- p/postgresql.sql
Capitalize keyword `as` to `AS`
> Update PostgreSQL example

- c/c++.cpp
I think we can keep this C++ example simple but remove some C++ bad practices like `using namespace std` or using a '\n' instead of a `std::endl`.
So, here is my contribution, I hope you will merge it and enjoy it.
> Improve C++ example

- README.md
- b/BAIK.ina
Added BAIK Programming Language
> Added BAIK

- README.md
- b/basic-256.kbs
> Added Basic-256

- README.md
- c/cbot.txt
.txt because .cbot extension doesn't work with game
> Added CBOT

- #/~Malay.ext
Malay language is from Malaysia country
> Added Malay translation

- #/~Italian.ext
- README.md
- c/c.c
- k/kotlin.kt
Added the **_Italian_** **_Translation_** of [~English.ext](https://github.com/leachim6/hello-world/blob/master/%23/~English.ext). Corrected [kotlin.kt](https://github.com/leachim6/hello-world/blob/master/k/kotlin.kt) and [c.c](https://github.com/leachim6/hello-world/blob/master/c/c.c) Also updated the [README.md](https://github.com/leachim6/hello-world/blob/master/README.md) file according to **_Italian.ext_**
> Added Italian and updated Kotlin

- README.md
- n/Night.night
A week ago, a language called [Night](https://github.com/DynamicSquid/Night) released its third version.
> Added Night

- #/~Turkish.ext
- README.md
> Add Turkish

- m/make.makefile
There is no need to use bash to print "Hello World" in Make. There is a language feature exactly for printing messages.
> Use Make feature instead of bash command

- README.md
- f/flutter.dart
Adds file to display **"Hello World"** in Flutter.
> Add Flutter

- c/csharp.cs
With [C# 9 and Top-level statements](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/top-level-statements), there's no need to define the `Program` class and `Main()` method.
Simple as that!
> Update C# to use top-level statements

- README.md
- a/ArkScript.ark
Added ArkScript language. You can find its source code [here](https://github.com/ArkScript-lang/Ark)
> Add ArkScript

- m/minecraft
If it is a simple text you don't have to put a JSON, a simple string is enough.
> Simplify Minecraft

- c/cache-objectscript.mac
- readme.md
[InterSystems Caché](https://docs.intersystems.com/latest/csp/docbook/Doc.View.cls?KEY=GIC_intro) is a commercial operational database management system from [InterSystems](https://www.intersystems.com/), used to develop software applications for healthcare management, banking and financial services, government, and other sectors.
> Add Caché ObjectScript

- #/~Afrikaans.ext
- readme.md
Added ~Afrikaans.ext and updated README.md
> Add Afrikaans

- c/cheese++.cheese
- readme.md
Info on cheese++ can be found [here](https://esolangs.org/wiki/Cheese%2B%2B).
> Add Cheese++

- readme.md
Just a minor spelling correction (from FizBuzz to FizzBuzz)
> Minor readme tweak

- e/emojicode.emojic
Made the emojicode file as simple as possible. It's successfully tested. 
Not sure why the last version was so long.
Check [here](https://www.emojicode.org/) for more info.
> Improve Emojicode

- HP_41C
- readme.md
> Add HP 41C

- p/perfume.prfm
- readme.md
Add new language.
[ref](https://github.com/mitchan0321/perfume)
> Add Perfume

- #/~German.ext
- readme.md
> Add German

- #/~German.ext
> Minor German tweak

- h/holyc.HC
> Update Holy C

- #/!@#$%^&*()_+
- readme.md
I got my code from [here](https://esolangs.org/wiki/!@$%25%5E%26*()%2B).
> Add !@#$%^&*()_+

- c/Coral 66.cor
- readme.md
Coral 66
Code from [here](http://www.xgc-tek.com/manuals/m68k-c66-gs/c140.html#p1node24). Fixes part of #790.
> Add Coral 66

- GreeeeeeeeenText
- g/GreeeeeeeeenText
- readme.md
> Add GreeeeeeeeenText

- d/Data Flex
- readme.md
> Add Data Flex

- readme.md
- z/ZScript
Add ZScript
Fixes part of: #790.
> Add ZScript

- d/Dragon
- readme.md
> Add Dragon

- readme.md
- u/Unreal Script.uc
> Add Unreal Script

- b/BuddyScript
- readme.md
> Add BuddyScript

- a/AutoLISP.lsp
- readme.md
> Add AutoLISP

- p/PeopleCode
- readme.md
> Add PeopleCode

- a/Assembler Z80 Knightos.asm
Remove comments, make it only play once and make it say "Hello World".
> Fix Assembler Z80 Knightos

- a/Assembler 6502c64.asm
- a/Assembler 6809vectrex.asm
- a/Assembler 8048 videopac.asm
- a/Assembler Bootsect.asm
- a/Assembler IBM360.asm
- a/Assembler Intel.asm
- a/Assembler MASM DOS.asm
- a/Assembler MASM Win32.asm
- a/Assembler MASM Win64.asm
- a/Assembler MIPS.asm
- a/Assembler NASM FreeBSD.asm
- a/Assembler NASM Linux.asm
- a/Assembler NASM Macho64.asm
- a/Assembler NASM Win32.asm
- a/Assembler TASM DOS.asm
- a/Assembler Vax Ultrix.asm
- a/Assembler Z80 Knightos.asm
- a/Assembler Z80 TI83calculator.asm
- a/Assembler Z80 zxspectrum.asm
- a/Assembler hla.hla
- a/Assembler lc3.asm
- a/Assembler m68000 amigaos.asm
- a/Assembler tms9900 ti99 4a.asm
> Fix Assembly files

- license
> Meta tweak

- p/Pinecone.pn
- readme.md
https://wmww.github.io/Pinecone/
> Add Pinecone

- b/Backshift
- readme.md
https://esolangs.org/wiki/Hello_world_program_in_esoteric_languages
Beginning space IS necessary!
> Add Backshift

- r/RISC V.s
- readme.md
> Add RISC-V

- i/Inform.inform
> Fix Inform

- m/Macsyma.mac
> Minor tweak

- c/CypherNeo4j.cypher
> Fix CypherNeo4j

- readme.md
- t/Takeover
> Add Takeover

- #/~Vietnamese.ext
- readme.md
> Add Vietnamese

- a/Angular.js
- c/Cor.cor
- e/EmacsLisp.el
> Meta tweaks

- l/LLVM.ll
> Minor tweaks

- e/Elixir.ex
> Fix Elixir

- p/Printscript
- readme.md
> Add Printscript

- c/Common Lisp.lisp
> Fix Common Lisp

- Boolet
- b/Boolet
- readme.md
> Add Boolet

- readme.md
> Add one-two-three...infinity to related

- c/Comefrom0x10
- readme.md
> Add Comefrom0x10

- readme.md
- s/SmileBASIC.bas
> Add SmileBASIC

- f/FROM HERE TO THERE
- readme.md
https://esolangs.org/wiki/FROM_HERE_TO_THERE
> Add FROM HERE TO THERE

- k/Kitanai
- readme.md
https://esolangs.org/wiki/Kitanai
> Add Kitanai

- n/Not Python
- readme.md
https://esolangs.org/wiki/Not_Python
> Add Not Python

- #/~Hungarian
- readme.md
> Add Hungarian

- m/Mostawesomeprograminglanguage
- readme.md
> Add Mostawesomeprogramminglanguage

- c/ContinuesEquation.ce
> Fix ContinuesEquation

- j/JScript.js
- readme.md
> Add JScript

- readme.md
- u/Underload.ul
SOURCE: https://esolangs.org/wiki/Underload
- [✔ ] The code displays "Hello World"
- [✔ ] I have updated the readme to include the new language
- [✔] I have incremented the language count in the readme
> Add Underload

- readme.md
- s/Snekky.snek
Website: [https://snekky-lang.org/](https://snekky-lang.org/)
> Add Snekky

- f/Fortran.f90
Greetings, I just stumbled upon this repository and realized the Fortran example can be improved by eliminating the unnecessary extra lines of code. This patch reduces the Fortran example HelloWorld code to only the minimal essential lines.
The existing example for Fortran
> Simplfying Fortran hello world example.

- c/Centura.centura
- d/DogeScript.djs
- g/Google Apps Script.gs
- h/Hack.hh
- h/Hubot.coffee
- k/Karel.kl
- p/PLSQL.sql
- p/PiCat.pi
Reverts leachim6/hello-world#1049
> Revert "Migrate to double quotes"

- c/Centura.centura
- d/DogeScript.djs
- g/Google Apps Script.gs
- h/Hack.hh
- h/Hubot.coffee
- k/Karel.kl
- p/PLSQL.sql
- p/PiCat.pi
Reverts leachim6/hello-world#1168 whoops made a big mistake 🤦😬
> Revert "Revert "Migrate to double quotes""

- a/Ansible.yml
- readme.md
> Add Ansible

- T Sharp.t#
- readme.md
- t/TSharp.t#
[Here's link to the language repo](https://github.com/Tsharp-lang/Tsharp)
> Add TSharp

- #/~Kinyarwanda
- readme.md
> Add Kinyarwanda

- d/Django.py
- readme.md
> Add Django

- #/~Kurdish
- readme.md
> Add Kurdish

- p/PLSQL.sql
- p/PL∕SQL.pls
- readme.md
Replace PLSQL.sql with new PL/SQL.pls.
> Fix PL/SQL

- r/ReScript.res
- readme.md
> Add ReScript

- x/XHTML.xhtml
Format XHTML code, to match the tab-based indenting used in all other code samples in this repo.
> Use tab-based indenting in XHTML code sample

- g/GitHub Actions.yaml
- readme.md
https://github.com/features/actions
> Add GitHub Actions

- a/ARTICLE.artl
- readme.md
https://github.com/SoicBRcode/article-lang
> Added ARTICLE

- g/GitHub Actions.yaml
Only the `workflow_dispatch` trigger is not enough, so I'm adding a `push` trigger to the workflow.
> Change GitHub Actions triggers

- g/GitHub Actions.yaml
Reverts leachim6/hello-world#1205
> Revert "Change GitHub Actions triggers"

- readme.md
- t/Tea.tea
https://github.com/tealang/tea
> Add Tea language

- readme.md
- s/Smallworld MAGIK.magik
> Add Smallworld MAGIK

- o/Oxygene.pas
- readme.md
> Add Oxygene

- b/Bottle.py
- readme.md
> Add Bottle

- m/Monkey
- readme.md
> Add Monkey

- l/LiveCode
- readme.md
> Add LiveCode

- c/Cherry.py
- readme.md
**fix to my previous pull request**
> Add CherryPy

- readme.md
- w/wxPython.py
> Add wxPython

- p/PySimpleGUI.py
- readme.md
> Add PySimpleGUI

- c/Come Here
- readme.md
> Add Come Here

- p/PySimpleGUI.py
> Use double quotes in PySimpleGUI

- b/Bottle.py
Made a quick edit to the Bottle code so now the user sees "Hello World" on the main page.
> Quick Bottle Edit

- #/6969 Assembler
- readme.md
> Add 6969 Assembler

- readme.md
- y/Yorick.i
https://github.com/LLNL/yorick
> Add Yorick

- n/NewLISP.lsp
- readme.md
> Add NewLISP

- n/NetRexx.nrx
- readme.md
> Add NetRexx

- h/Harbour.prg
- readme.md
> Add Harbour

- b/Ballerina.bal
> Fix Ballerina

- b/Bhai Lang.bhai
- readme.md
> Added Bhai Lang

- c/ChaScript
- readme.md
> Add ChaScript

- c/CEBL.ceb
- readme.md
http://cebl.taart.site/
http://cebl.taart.site/board/
> Added CEBL (Common English Based Language)

- m/Manim.py
- readme.md
> Add Manim.py

- readme.md
- t/Terraform.tf
> Add Terraform IAC DSL

- m/Maxima.max
- readme.md
[https://maxima.sourceforge.io/](https://maxima.sourceforge.io/)
```sh
maxima -b m/Maxima.max
```
> Add Maxima

- readme.md
- u/uwu.uwupp
added hello world in Uwu Language
> Add uwu language

- readme.md
- z/ZSharp.zs
https://esolangs.org/wiki/Z_Sharp
https://github.com/sam-astro/Z-Sharp
> Add ZSharp

- g/Gleam.gleam
- readme.md
- w/Wax.wax
https://github.com/LingDong-/wax
https://github.com/gleam-lang/gleam
> Add Wax and Gleam

- .github/workflows/update_readme.yml
- contributing.md
Added Automatic readme updater.
Contributors doesn't need to update readme by them self anymore
> Auto readme updater

- m/MicroPython.py
- readme.md
> Micro python

- m/Mojo.🔥
- readme.md
> Added Mojo

- g/Goldfish.gfi
- readme.md
> Add Goldfish

- b/Brainrot.brainrot
- readme.md
[brainrotlang.com](https://brainrotlang.com/)
> Add Brainrot
