leachim6/hello-world

f/forth.f
f/forth.fth

The Forth program uses a non-standard word `TELL`.  Also, it's simpler to use `."` than `S"` and print the result.  Also, the `.f` file extension may clash with Fortran.

Convert to Standard Forth.

---

t/telephone

A standard telephone keyboard uses "6" for "O", not "0". Do the same here.
For evidence of this being standard, see ISO/IEC 9995-8:2009 or E.161.

Use standard telephone keyboard layout

---

w/whitespace.ws

[The disassembly of the current program](https://gist.github.com/0x0dea/f68d381ed844f85fa2bd) clearly indicates that it was generated by a machine, which is, I think, not in the spirit of the project. This patch replaces the existing program with a more idiomatic one which, in addition to being smaller and faster, masquerades as a sequence of assembly instructions while remaining an executable Whitespace program.

Improve Whitespace

---

a/apl.apl

The existing declaration does nothing but generate syntax errors in the GNU APL interpreter. No idea about other interpreters like Dyalog, etc.

Replace ASCII APL with correct Unicode characters

---

l/lisp.lsp

Previous version defined a function but didn't call it.

Update to call the function

---

c/common-lisp.lisp

Common Lisp is distinct from plain old `Lisp' in that
Lisp doesn't have FORMAT.  That was added in Common Lisp,
in Guy Steele's book Common Lisp the Language, in 1984.

Add Common Lisp example

---

README.md
list_langs.rb

As I previously noted CONTRIBUTING.md, simply execute list_langs.rb (using the command in CONTRIBUTING.md!!) yourself anytime you want to update the listing.

Fixed list_langs.rb and executed it

---

p/processing.pde

By itself, the previous Processing sketch just displays a black background. That's because the colour of the text is black by default. So to make it visible, I added `fill(255)` to change the text's colour to white.

Why not make the text visible?

---

list_langs.py

This closes #395. The old version of `list_langs.py` only worked on Python 3.6 because it used the new "f-strings." As was pointed out in #395, Python 3.6 does not yet have widespread use and it's nice to maintain compatibility with older Python versions so that more people can use it and develop with it.
My new version of the script was tested on Python 3.5.2 and Python 2.7.12

Compatibility with older versions of Python

---

list_langs.py

[`dir`](https://docs.python.org/3/library/functions.html#dir) is a Python built-in function, [`str`](https://docs.python.org/3/library/stdtypes.html#str) is a Python built-in type, and `file` was a built-in type until it was [removed in Python 3.0](https://docs.python.org/release/3.0/whatsnew/3.0.html#builtins). Therefore, it is generally considered bad practice to name variables with these names, since those variables then overshadow and prevent the use of `str()`, `dir()`, and `file()`.

Rename variables in list-langs.py

---

p/powershell.ps1

Default behavior of PowerShell is to send any objects at end of pipeline to output.
There is no need to explicitly call Write-Output cmdlet.
Fixes #416

Remove Write-Output call from PowerShell example

---

c/coffeescript.coffee

Coffeescript documentation uses _alert_ for messages rather than _console.log_

Update coffeescript.coffee to use alert

---

a/ada.ada

The Text_IO package was Ada 83. Afterwards it is Ada.Text_IO.
The package is 'opened' with 'use Ada.Text_IO'
Conforming to usual style.

Update Ada example

---

README.md
e/enkelt.e

Added Hello World for the **Enkelt** language (https://enkelt.io). 
Note: *The ATS2 link in the README was apparently not supposed to be in all caps,  cause the update_list script changed it to lower case.*

Added Enkelt

---

m/Minecraft.mcfunction

Removed the `/` at the start of the first line due to the fact that MCF won't run any lines that start with `/`

Fix Minecraft

---

a/Assembler lc3.asm

The current LC-3 program does not halt after the PUTS, so it will then try to execute 'H', or 0x0048 as a word. This gets decoded as a branch to PC+0x48, but one that is never taken. Some simulators may reject this, as my humble implementation does on the basis that there's no way to write that in LC-3 assembly (the assembler interprets br as brnzp). Even if they treat each character of the .stringz as a no-op, the CPU would keep executing no-ops afterward (if memory is initialized to zero) or undefined behavior (if memory is not). So add a HALT to try and avoid weird behavior.
Also added a .end as some assemblers (such as my prototype which is very picky) will complain if you don't have one
Tested with https://ausb.in/novice/

Fix Assembler lc3

---

w/WikiText
w/Wikitext.wiki

GitHub renders Wikitext syntax for files whose name ends with `.wiki`, `.wikitext`, or `.mediawiki`.

Rename WikiText to Wikitext.wiki

---

r/R.R

`\n` adds a newline, which contributing.md says to avoid if possible, without `\n`, there is no newline.

Avoid printing newline in R

---

p/PowerShell.ps1

Write-Host is superfluous, because PowerShell sends objects (including "Hello, World" text) to output stream ("stdout") by default.
More information can be found [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_output_streams).

Fix: PowerShell writes to output stream by default

---

c/ChinesePython.py

Fix ChinesePython

---

c/Coq.v
readme.md

Adding Coq hello world program
